### ISSUE TITLE
Introduce Support for Ubuntu 16.04 

### ISSUE THREAD

**Issue by gmolto** [indigo-dc/ansible-role-docker#4]
Hi,

We where doing some tests to deploy a Mesos cluster on AWS, which uses this role but the deployment fails with the following error:

TASK [indigo-dc.docker : Fail if OS distro is not Ubuntu 14.04] ****************
fatal: [34.198.199.10_22]: FAILED! => {"changed": false, "failed": true, "msg": "The role is designed only for Ubuntu 14.04"}

Can we have support for Ubuntu 16.04 for this role. 

Thank you very much in advance.

**Comment by maricaantonacci** [comment]
Sure. The support will be added soon.

**Comment by maricaantonacci** [comment]
Merged https://github.com/indigo-dc/ansible-role-docker/pull/6
